---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-lam2mo
  template:
    metadata:
      labels:
        app: birds-app-back-end-lam2mo
    spec:
      containers:
        - image: 'ghcr.io/lam2mo/birds-app-back-end:3dde4cc394e692bda6d5b5d638dd6395b521fc27'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
