---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-front-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-front-end-lam2mo
  template:
    metadata:
      labels:
        app: birds-app-front-end-lam2mo
    spec:
      containers:
        - image: 'ghcr.io/lam2mo/birds-app-front-end:6a1f13137e0e664e2fb7d12a0497ccc5228deb14'
          name: birds-app-front-end
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
